### ISSUE TITLE
关于写书源js文件的疑问

### ISSUE THREAD

**Issue by Bet76kg** [SJJ-dot/Reader#12]
用什么工具写这样的书源js可以出现自动提示呢，用as很多属性点不出来，格式化代码格式也无效，调试起来很不方便；

**Comment by SJJ-dot** [comment]
vscode的提示稍微好一些，可以安装提示插件，但是帮助不是很大。我平常编写书源也是通过as复制其他的书源改改。

**Comment by SJJ-dot** [comment]
你有什么好的建议吗？🌝

**Comment by Bet76kg** [comment]
没有呢，你这种调用js的方式，也是第一次见，最早看了阅读的书源，本想单独抽出来，但是写的太复杂了，很难上手。你这种，熟悉的话，常用的网站半个小时左右就能写好啦。

**Comment by SJJ-dot** [comment]
😏，我前段时间想做阅读书源的兼容。🌝🌝🌝

**Comment by Bet76kg** [comment]
大神，能兼容是最好的，毕竟它的书源很多，一来也有自己的特色，也可以兼容阅读搜遍全网🌝

**Comment by SJJ-dot** [comment]
总有语法看不懂就放弃了🌝🌝🌝🌝🌝

**Comment by Bet76kg** [comment]
确实复杂。不过你这个有人完善书源的话，也不差😏
