### ISSUE TITLE
用了很久，但是有时候有些书搜不到，请问可以把书站脚本单独用个地址维护吗？

### ISSUE THREAD

**Issue by tearslee** [SJJ-dot/Reader#3]
一些小说网站比如
http://www.banzhuer.org/
http://www.changshengrui.com/
的资源偶尔能补充其他站点的资源问题。

**Comment by SJJ-dot** [comment]
站点我抽空加上去，脚本地址问题有建议吗？。

**Comment by SJJ-dot** [comment]
其实现在也是可以在网络加载脚本的，脚本页右上角下载按钮就是在当前的存储库检查脚本更新。只是需要手动检查。
因为用户比较少，也没有其他的作者参与，并且编写新的脚本难免需要运行环境调试，所以就隐藏了脚本地址的填写入口。
后面我会将脚本放到 issue 里面，启动app后自动检测。

**Comment by tearslee** [comment]
好的，谢谢您的回复。

**Comment by SJJ-dot** [comment]
还有个问题是国内并不是每次都能成功的打开GitHub的网站，将脚本放在这里的话即使更新了脚本客户端也不一定能够及时获取到更新………………

**Comment by tearslee** [comment]
额，目前能够使用你的项目的人应该都有科学上网的能力吧（😀）。

**Comment by SJJ-dot** [comment]
脚本更新是不定时的，科学上网也不是一直开的，所以说反而是内置脚本直接更新app，推送更及时一点
。

**Comment by SJJ-dot** [comment]
最新的版本对书源进行了优化。可以自己编写书源了。 @tearslee
